### ISSUE TITLE
homepage docs say to use 'raw' instead of 'html' for styled messages

### ISSUE THREAD

**Issue by johnsogg** [adopted-ember-addons/ember-notify#109]
The homepage docs at http://simonwade.me/ember-notify currently have this for writing styled messages:

```
Notify.info({raw: '<div class="my-div">Hooray!</div>'});
```

It should be:

```
Notify.info({html: '<div class="my-div">Hooray!</div>'});
```

The Github readme has it right though, which is how I spotted the bug.

**Comment by btecu** [comment]
The website doesn't exist anymore.
