### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by Nippius** [adopted-ember-addons/ember-notify#113]
Hi,

Could someone upgrade de required dependencies for this project? 
The latest version of ember (>=2.18) throws deprecated warnings because this (and other) addons are using a deprecated version of ember-cli-version-checker directly or indirectly.

In particular, the packages that seem to be causing trouble are:

- ember-cli-babel
- ember-cli-htmlbars

Thank you

**Comment by scottkidder** [comment]
:tada:

```
warning git+ssh://git > ember-notify > ember-cli-babel@5.2.5: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0
warning git+ssh://git > ember-notify > ember-string-ishtmlsafe-polyfill > ember-cli-babel@5.2.5: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0
```
