### ISSUE TITLE
Assertion Failed: Attempted to call .send() with the action 'closeIntent' on the destroyed object

### ISSUE THREAD

**Issue by solominsn** [adopted-ember-addons/ember-notify#120]
Hello, I've updated to Ember 3.2 and noticed an error message from `ember-notify`. I cannot say that the problem connected with Ember version because I unable to roll back to Ember 2.x and to my old code.

Ember error happens when try to close notification by close action. I've looked at to source code and found logical error which seems not connect with Ember version.
What happens:
1. `close` action changes `visible` to `false` and start `remove` function asynchronously
2. Visible observer sends `closeIntent`.
3. `closeIntent` checks element hovering (and notification is hovered because mouse pointer is under close button) and starts "later" task which will call `closeIntent` action again.
4. Async repeating happens several times (dependent of animation duration).
5. After `remove` function (from 1) execution message is destroyed, but closeIntent's "later" task still asynchronously call `closeIntent` action without checking => ember write assert to console.

But root cause of this problem is we shouldn't try to close message when it's already closed. So `message.closed` checking should be added to `closeIntent`, `close` actions and `visibleObserver`.

**Comment by scottkidder** [comment]
Are there any existing efforts to fix this?

**Comment by coolheinze** [comment]
As latest commit is from July 2nd, this is still a problem. Any plans on fixing it?

**Comment by btecu** [comment]
Can someone put together a reproduction (ideally a test)?

**Comment by btecu** [comment]
I believe this issue is fixed after https://github.com/adopted-ember-addons/ember-notify/pull/135.
