### ISSUE TITLE
Can you make a new patch release ? 

### ISSUE THREAD

**Issue by danielspaniel** [adopted-ember-addons/ember-notify#122]
I want to get the latest on master ( I know I can put #master in package.json ). But this addon has not had new release it a year, and it's about time .. no?  
 You've updated ember-cli-babel and apps now adays kinda needs that to avoid the deprecation errors.

**Comment by arthur5005** [comment]
Agreed, it's 2019! The future is now!

**Comment by btecu** [comment]
There is a new version, https://github.com/adopted-ember-addons/ember-notify/releases/tag/6.0.0 which fixes all existing deprecations in addition to removing jQuery dependency and other enhancements.
