### ISSUE TITLE
Notification messages do not close in IE11

### ISSUE THREAD

**Issue by drouhard** [adopted-ember-addons/ember-notify#123]
Messages no longer close in IE11 either after a timeout or when clicking the close button. They just persist indefinitely.

I suspect this changed when [jQuery was removed](https://github.com/aexmachina/ember-notify/commit/d4ac0ae9923d28effdbb1c39c9cd2af6dbafebb0), as I see at least one replacement that isn't supported by IE.

For example, using the [matches selector](https://github.com/aexmachina/ember-notify/commit/d4ac0ae9923d28effdbb1c39c9cd2af6dbafebb0#diff-d5a2e62748aaf28e7439e392422147deR62) is not supported by IE11 without prefixing (see [this caniuse entry](https://caniuse.com/#feat=matchesselector))

**Comment by btecu** [comment]
The cause is IE not having `Element.matches` but `Element.msMatchesSelector`:
https://github.com/aexmachina/ember-notify/blob/master/addon/components/ember-notify/message.js#L65

**Comment by bryanhickerson** [comment]
@btecu Is there a way to polyfill `matches` for ember-notify? I'd be happy to open a pr, but I'm not sure how to go about it. Otherwise we're going to be stuck on ember-notify 5.2.1, which is using a deprecated version of babel.

**Comment by btecu** [comment]
@bryanhickerson You actually don't need to polyfill `matches` because IE 11 already supports it, it just has a different name.

Somewhere in your application:
```js
if (!Element.prototype.matches) {
  Element.prototype.matches = Element.prototype.msMatchesSelector;
}
```

**Comment by bryanhickerson** [comment]
@btecu Ah, thanks. It seems like that should live in ember-notify. I'll open PR with that change.
