### ISSUE TITLE
DEPRECATION: `hasBlock` is deprecated. Use `has-block` instead.

### ISSUE THREAD

**Issue by esbanarango** [adopted-ember-addons/ember-notify#163]
**DEPRECATION:** 

`hasBlock` is deprecated. Use `has-block` instead. ('ember-notify/templates/components/ember-notify/message.hbs' @ L1:C6)  [deprecation id: has-block-and-has-block-params] See https://emberjs.com/deprecations/v3.x#toc_has-block-and-has-block-params for more details.

**Comment by bertdeblock** [comment]
@btecu I see you made a commit for this deprecation on your fork. Were you planning on making a PR for this? Otherwise I can do this as well.

**Comment by btecu** [comment]
@bertdeblock I merged that pull request. The change likely requires a major release, since `hasBlock` was deprecated recently.
However, to release a new version we should fix the tests (https://github.com/adopted-ember-addons/ember-notify/issues/136). Would you be able to help with that?

**Comment by bertdeblock** [comment]
Thanks for merging! I don't think it requires a major release though. [`{{hasBlock}}` was an alias for calling `{{has-block}}` without a block name or for calling it with the block name `default`](https://github.com/emberjs/rfcs/pull/689/files#diff-5614e1898359c3aa6fe4feb634d860fef3e41295531dcf1549a9ccb825152076R23-R25).

**Comment by btecu** [comment]
@bertdeblock `6.0.1` has been released.

**Comment by esbanarango** [comment]
Thank you 🙏
