### ISSUE TITLE
Any plans with releasing the latest changes?

### ISSUE THREAD

**Issue by GabrielCousin** [adopted-ember-addons/ember-notify#178]
Hey, all!
We ran into some issues (not really related to the package though) after upgrading to Ember 3.28 ([this change](https://github.com/adopted-ember-addons/ember-notify/commit/9dabbd3b2f85584df7bf580c1bf15f7b1d0a8912) is solving our issue). Despite that import change was supposed to be a [deprecation](https://deprecations.emberjs.com/v3.x#toc_ember-string-htmlsafe-ishtmlsafe) so far, it stopped suddenly with the code shipped with ember-notify 6.0.1.
Again, using the latest commit from master solved the issue.
Do you plan to release these shortly or do you have any other issues in mind?
Thank you so much!

**Comment by btecu** [comment]
@GabrielCousin [6.0.2](https://github.com/adopted-ember-addons/ember-notify/releases/tag/v6.0.2) has been released.

**Comment by GabrielCousin** [comment]
Fantastic! Thank you
