### ISSUE TITLE
<emberNotify::Message> is not a component and doesn't support block parameters

### ISSUE THREAD

**Issue by FutoRicky** [adopted-ember-addons/ember-notify#196]
I am getting this issue when upgrading from version 5.3.0. This is probably not an issue with the addon itself, but I am unable to resolve this issue. Any idea as to why this error message is appearing? My ember-cli version is 3.26.1, could this be the issue?

Thank you in advance.

**Comment by btecu** [comment]
Should just be `<EmberNotify />`.
What exactly are you trying to do?

**Comment by FutoRicky** [comment]
That's my issue, I changed all the ember-notify block parameters to `<EmberNotify />` and I keep getting this error

**Comment by FutoRicky** [comment]
This is the complete error:

```
Template Compiler Error (TemplateCompiler) in ember-notify/templates/components/ember-notify.hbs

Compile Error: <emberNotify::Message> is not a component and doesn't support block parameters


Stack Trace and Error Report: /tmp/error.dump.0b95dab4f007e05c8c34d58433fe3c0d.log
Template Compiler Error (TemplateCompiler) in ember-notify/templates/components/ember-notify.hbs

Compile Error: <emberNotify::Message> is not a component and doesn't support block parameters


Stack Trace and Error Report: /tmp/error.dump.534f3180e2e1b0b1e201747aedebd017.log
```

It seems the error is from the addon itself, but when I go into it, it's not using block parameters.

**Comment by FutoRicky** [comment]
The issue is the app was not octane enabled.
